bash

diff --git a/eng/pipelines/templates/steps/template-test-run-job.yml b/eng/pipelines/templates/steps/template-test-run-job.yml
--- a/eng/pipelines/templates/steps/template-test-run-job.yml
+++ b/eng/pipelines/templates/steps/template-test-run-job.yml
@@ -69,7 +69,7 @@ steps:
       ARM_CLIENT_SECRET=$(arm-client-secret)
       ARM_TENANT_ID=$(arm-tenant-id)
       SUBSCRIPTION_ID=$(SubscriptionId)
-    runCmd: 
+    runCmd: |
       echo "path"
       pwd
       echo "azd version"
@@ -79,19 +79,101 @@ steps:
         --client-secret "$(arm-client-secret)" \
         --tenant-id "$(arm-tenant-id)"
 
-    targetType: filePath
-    filePath: templates/tests/test-templates.sh
-    arguments: >
-      -f '$(Pipeline.Workspace)'
-      -e '$(EnvPrefixName)'
-      -t '$(TemplateName)'
-      -b '$(TemplateBranchName)'
-      -s '$(SubscriptionId)'
-      -u '$(Build.BuildId)'
-      -l '$(AzureLocation)'
-      -p 'list'
-      -c '$(SynchronousCleanup)'
-    workingDirectory: templates/tests
+      set -euo pipefail
+      FOLDER_PATH=$(Pipeline.Workspace)
+      BRANCH_NAME=$(TemplateBranchName)
+      ENV_NAME_PREFIX=$(EnvPrefixName)
+      TEMPLATE_NAME=$(TemplateName)
+      PLAYWRIGHT_RETRIES="1"
+      PLAYWRIGHT_REPORTER='list'
+      LOCATION=$(AzureLocation)
+      SUBSCRIPTION=$(SubscriptionId)
+      ENV_SUFFIX=$(Build.BuildId)
+      TEST_ONLY=false
+      CLEANUP=$(SynchronousCleanup)
+
+      function deployTemplate {
+          echo "Creating new project folder @ '$FOLDER_PATH/$3'..."
+          cd "$FOLDER_PATH"
+          mkdir "$3"
+          cd "$3"
+
+          echo "Initializing template '$1' with branch '$2'"
+          azd init -t "$1" -b "$2" -e "$3" --subscription "$4" --location "$5" --no-prompt
+
+          echo "Provisioning infrastructure for $3..."
+          azd provision -e "$3"
+
+          echo "Deploying apps for $3..."
+          azd deploy -e "$3"
+      }
+
+      function testTemplate {
+          echo "Running template smoke tests for $3..."
+          cd "$FOLDER_PATH/$3/tests"
+          npm i && npx playwright install
+          npx -y playwright test --retries="$PLAYWRIGHT_RETRIES" --reporter="$PLAYWRIGHT_REPORTER"
+      }
+
+      function cleanupTemplate {
+          echo "Deprovisioning infrastructure for $3..."
+          cd "$FOLDER_PATH/$3"
+          azd down -e "$3" --force --purge
+
+          echo "Cleaning up local project @ '$FOLDER_PATH/$3'..."
+          rm -rf "$FOLDER_PATH/${3:?}"
+      }
+
+      if [[ -z $TEMPLATE_NAME ]]; then
+          declare -A ENV_TEMPLATE_MAP
+
+          echo "Getting list of available templates..."
+          TEMPLATES_JSON=$(azd template list --output json)
+
+          while read -r TEMPLATE; do
+              ENV_NAME="${ENV_NAME_PREFIX}-${TEMPLATE:14}-$ENV_SUFFIX"
+              ENV_TEMPLATE_MAP[$TEMPLATE]=$ENV_NAME
+          done < <(echo "$TEMPLATES_JSON" | jq -r '.[].name' | sed 's/\\n/\n/g')
+
+          if [ $TEST_ONLY == false ]; then
+              # Deploy the templates in parallel
+              for TEMPLATE in "${!ENV_TEMPLATE_MAP[@]}"; do
+                  (deployTemplate "$TEMPLATE" "$BRANCH_NAME" "${ENV_TEMPLATE_MAP[$TEMPLATE]}" "${SUBSCRIPTION}" "${LOCATION}" || continue) &
+              done
+
+              wait
+          fi
+
+          # Test the templates serially
+          for TEMPLATE in "${!ENV_TEMPLATE_MAP[@]}"; do
+              testTemplate "$TEMPLATE" "$BRANCH_NAME" "${ENV_TEMPLATE_MAP[$TEMPLATE]}" || continue
+          done
+
+          if [ "$CLEANUP" == true ]; then
+              # Cleanup the templates in parallel
+              for TEMPLATE in "${!ENV_TEMPLATE_MAP[@]}"; do
+                  (cleanupTemplate "$TEMPLATE" "$BRANCH_NAME" "${ENV_TEMPLATE_MAP[$TEMPLATE]}" || continue) &
+              done
+
+              wait
+          fi
+
+          echo ""
+          echo "Done!"
+      else
+          # Run test for the specified template name
+          ENV_NAME="${ENV_NAME_PREFIX}-${TEMPLATE_NAME:14}-$ENV_SUFFIX"
+          if [ $TEST_ONLY == false ]; then
+              deployTemplate "$TEMPLATE_NAME" "$BRANCH_NAME" "$ENV_NAME" "${SUBSCRIPTION}" "${LOCATION}" 
+          fi
+
+          testTemplate "$TEMPLATE_NAME" "$BRANCH_NAME" "$ENV_NAME"
+
+          if [ "$CLEANUP" == true ]; then
+              cleanupTemplate "$TEMPLATE_NAME" "$BRANCH_NAME" "$ENV_NAME"
+          fi
+      fi
+
     
 
 - template: /eng/pipelines/templates/steps/az-login.yml
